services:
  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: encogix
    ports:
      - "3306:3306"
    volumes:
      - encogix_mysql_data:/var/lib/mysql

volumes:
  encogix_mysql_data:
